In [1]:
import numpy as np
import pandas as pd

In [3]:
# set random seed for reproducibility
np.random.seed(123)

In [4]:
# create dataframe with two classes
n_samples = 1000
class_0_ratio = 0.9
n_class_0 = int(n_samples*class_0_ratio)
n_class_1 = n_samples - n_class_0

In [5]:
# create my dataset with imbalanced dataset
class_0 = pd.DataFrame({
    'feature_1': np.random.normal(loc=0, scale=1, size=n_class_0),
    'feature_2': np.random.normal(loc=0, scale=1, size=n_class_0),
    'target': [0]*n_class_0
})
class_1 = pd.DataFrame({
    'feature_1': np.random.normal(loc=0, scale=1, size=n_class_1),
    'feature_2': np.random.normal(loc=0, scale=1, size=n_class_1),
    'target': [1]*n_class_1
})

In [6]:
df = pd.concat([class_0, class_1]).reset_index(drop = True)

In [7]:
df.head()

   feature_1  feature_2  target
0  -1.085631   0.551302       0
1   0.997345   0.419589       0
2   0.282978   1.815652       0
3  -1.506295  -0.252750       0
4  -0.578600  -0.292004       0

In [8]:
df['target'].value_counts()

target
0    900
1    100
Name: count, dtype: int64

## UpSampling

In [10]:
df_minority = df[df['target']==1]
df_majority = df[df['target']==0]

In [11]:
from sklearn.utils import resample

In [20]:
df_minority_update = resample(
    df_minority, replace = True, # sample with replacement
    n_samples = len(df_majority),
    random_state = 42
)

In [21]:
df_minority_update.shape

(900, 3)

In [22]:
df_minority_update.head()

     feature_1  feature_2  target
951  -0.874146  -0.156083       1
992   0.196570  -0.602575       1
914  -0.067830   0.998053       1
971   0.272825   1.034197       1
960   0.870056  -0.449515       1

In [23]:
df_upsampled = pd.concat([df_majority, df_minority_update])

In [24]:
df_upsampled['target'].value_counts()

target
0    900
1    900
Name: count, dtype: int64

## DownSampled

In [19]:
df_minority = df[df['target']==1]
df_majority = df[df['target']==0]

In [25]:
df_majority_update = resample(
    df_majority, replace = False, # sample with replacement
    n_samples = len(df_minority),
    random_state = 42
)

In [26]:
df_majority_update.shape

(100, 3)

In [27]:
df_downsampled = pd.concat([df_minority, df_majority_update])

In [28]:
df_downsampled['target'].value_counts()

target
1    100
0    100
Name: count, dtype: int64